{"name": "test_multiple[1-2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n  +2\n  -3", "trace": "self = <test_cal.TestCalculator object at 0x0000017CA0F3C340>, a = 1, b = 2, exc = 3\n\n    @pytest.mark.parametrize('a,b, exc', get_data('data.json')[\"param\"]['mul'])\n    @pytest.mark.flaky(reruns=2, reruns_delay=1)\n    @pytest.mark.run(order=3)\n    def test_multiple(self, a, b, exc):\n        result = self.c.multiple(a, b)\n>       assert result == exc\nE       assert 2 == 3\nE         +2\nE         -3\n\ntest_cal.py:78: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "exc", "value": "3"}], "start": 1615726259774, "stop": 1615726259774, "uuid": "0a6bb8bd-e759-4d91-8c05-e4294b80b0ce", "historyId": "81119bc82169c4eb76f60a22aff96251", "testCaseId": "17e3bc447fa282888c694bd6ee46b98e", "fullName": "test_cal.TestCalculator#test_multiple", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "flaky(reruns=2, reruns_delay=1)"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}