{"name": "test_add[2-4-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 5\n  +6\n  -5", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0C714C0>, a = 2, b = 4, exc = 5\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_add(self, a, b, exc):\n        result = self.c.add(a, b)\n>       assert result == exc\nE       assert 6 == 5\nE         +6\nE         -5\n\ntest_calculator.py:24: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "4"}, {"name": "exc", "value": "5"}], "start": 1615726260967, "stop": 1615726260967, "uuid": "8ed6b3e5-2ec4-4d5b-ba05-3b7aaa1c870f", "historyId": "cbb434285b9572dcf1c70ab9c333ddba", "testCaseId": "c0380ad0f93ea623c2328a25b0918ec2", "fullName": "test_calculator.TestCalculator#test_add", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}