{"name": "test_multiple[1-2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n  +2\n  -3", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0D77AC0>, a = 1, b = 2, exc = 3\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_multiple(self, a, b, exc):\n        result = self.c.multiple(a, b)\n>       assert result == exc\nE       assert 2 == 3\nE         +2\nE         -3\n\ntest_calculator.py:44: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "exc", "value": "3"}], "start": 1615726260934, "stop": 1615726260934, "uuid": "af35763e-3ac8-4679-9ad5-f921fd11d6a9", "historyId": "2256794ec199c0f18a16c941a84a53e5", "testCaseId": "695a72d0b9108d87efdf02f91f38cbda", "fullName": "test_calculator.TestCalculator#test_multiple", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}