{"name": "test_minus[1-2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -1 == 3\n  +-1\n  -3", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0F3CF10>, a = 1, b = 2, exc = 3\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_minus(self, a, b, exc):\n        result = self.c.minus(a, b)\n>       assert result == exc\nE       assert -1 == 3\nE         +-1\nE         -3\n\ntest_calculator.py:34: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "exc", "value": "3"}], "start": 1615726260955, "stop": 1615726260955, "uuid": "8e4cb27a-85ad-4537-8937-1fd003cd9237", "historyId": "5298330b05d2e0e033916a04367144ba", "testCaseId": "7b480cf393e9b022b332fec743686f40", "fullName": "test_calculator.TestCalculator#test_minus", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}